apps/archive/urls.py
from django.urls import path

from .views import ArchiveList, ArchiveDetail

urlpatterns = [
    path("", ArchiveList.as_view(), name="list"),
    path("<slug:slug>/", ArchiveDetail.as_view(), name="detail"),
]

nablarevyen/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("", include(("apps.frontpage.urls", "frontpage"))),
    path("nyheter/", include(("apps.articles.urls", "articles"))),
    path("om-oss/", include(("apps.about.urls", "about"))),
    path("arkiv/", include(("apps.archive.urls", "archive"))),
    path("opptak/", include(("apps.applications.urls", "applications"))),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("admin/", admin.site.urls),
    path("bounce/", include("apps.bounce.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/archive/models.py
from django.db import models
from django.urls import reverse
from image_cropping import ImageRatioField
from embed_video.fields import EmbedVideoField


class Archive(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    display_in_menu = models.BooleanField(
        help_text='Set this to display in the archive menu. Otherwise found under "Read more"'
    )
    published = models.BooleanField(help_text="Set this to publish the entire archive")
    keywords = models.CharField(max_length=200)
    description = models.TextField(
        max_length=2000, help_text="Short description of the archive, 2000 symbols."
    )
    thumbnail_image = models.ImageField(
        upload_to="archive/archive/",
        help_text="To crop the image, simply click save and continue.",
    )
    thumbnail_image_crop = ImageRatioField(
        "thumbnail_image", "400x400", size_warning=True
    )

    def __str__(self):
        return "%s" % (self.name)


class Image(models.Model):
    archive = models.ForeignKey("Archive", on_delete=models.CASCADE)
    alt = models.CharField(max_length=50)
    description = models.TextField(
        max_length=200, help_text="Short description of the image, 200 symbols."
    )
    image = models.ImageField(
        upload_to="archive/images/",
        help_text="To crop the image, simply click save and continue.",
    )
    image_crop = ImageRatioField("image", "400x400", size_warning=True)

    def __str__(self):
        return "%s" % (self.alt)


class Video(models.Model):
    archive = models.ForeignKey("Archive", on_delete=models.CASCADE)
    alt = models.CharField(max_length=50)
    description = models.TextField(
        max_length=200, help_text="Short description of the video, 200 symbols."
    )
    link = EmbedVideoField()

    def __str__(self):
        return "%s" % (self.alt)

apps/archive/views.py
from django.views.generic import ListView, DetailView
from .models import Archive


class ArchiveList(ListView):
    model = Archive
    queryset = Archive.objects.filter(published=True).order_by("name").reverse()
    paginate_by = 12
    page_kwarg = "side"


class ArchiveDetail(DetailView):
    model = Archive
    queryset = Archive.objects.filter(published=True)

apps/archive/templates/archive/archive_detail.html
{% extends "base.html" %}
{% load cropping %}
{% load embed_video_tags %}

{% block title %}{{ archive.name }} | Nablarevyen{% endblock %}

{% block header %}
{% include 'header.html' with active='archive' %}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block stylesheet %}
<style>
.archive-images {
  list-style: none;
}
.archive-images > li:hover {
  cursor: -moz-zoom-in;
  cursor: -webkit-zoom-in;
  cursor: zoom-in;
}
</style>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
  const gallery = new Viewer(document.getElementById('archive-gallery'), {
    url: 'data-original',
  });
</script>
{% endblock %}

{% block content %}
<div class="container mt-2 mb-2 p-3 bg-white border">
  <h2>{{ archive.name }}</h2>
  <p>{{ archive.description }}</p>
  <hr>
  <div id="archive-gallery">
    <ul class="row p-0 m-0 archive-images" style="list-style: none;">
      {% for image in archive.image_set.all %}
        <li class="col-6 col-sm-4 col-md-2 p-0 m-0 border border-white">
          <img class="img-fluid" data-original="{{ image.image.url }}" src="{% cropped_thumbnail image 'image_crop' %}" alt="{{ image.alt }}">
        </li>
      {% empty %}
        <p class="text-muted mx-auto mb-0"><em>Ingen bilder er publisert</em></p>
      {% endfor %}
    </ul>
  </div>
  <hr class="m-0 mt-3 mb-3">
  <div class="row p-0 m-0">
  {% for video in archive.video_set.all %}
    {% video video.link is_secure=True as my_video %}
      <div class="col-12 col-sm-6 col-md-4 p-1">
        <iframe width="100%" height="250px" src="{{ my_video.url }}" frameborder="0" allowfullscreen></iframe>
      </div>
    {% endvideo %}
  {% empty %}
    <p class="text-muted mx-auto mb-0"><em>Ingen videoer er publisert</em></p>
  {% endfor %}
  </div>
</div>
<div class="container mt-2 mb-2 p-3 bg-white border">
  <nav aria-label="breadcrumb mb-0">
    <ol class="breadcrumb mb-0">
      <li class="breadcrumb-item"><a href="{% url 'frontpage:index' %}">Forsiden</a></li>
      <li class="breadcrumb-item"><a href="{% url 'archive:list' %}">Arkiv</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ archive.name }}</li>
    </ol>
  </nav>
</div>
{% endblock %}

apps/archive/templates/archive/archive_list.html
{% extends "base.html" %}
{% load cropping %}

{% block title %}Arkiv | Nablarevyen{% endblock %}

{% block header %}
{% include 'header.html' with active='archive' %}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block content %}
<div class="container mt-2 mb-2 p-3 bg-white border">
  <h2>Arkiv</h2>
  <hr class="m-0 mb-3">
  <div class="row">
  {% for archive in archive_list %}
    {% if archive.published %}
      <div class="col-6 col-md-3 mb-4">
        <a class="text-dark" href="{% url 'archive:detail' archive.slug %}">
        <img class="card-img-top border border-secondary rounded-0" src="{% cropped_thumbnail archive 'thumbnail_image_crop' %}" alt="Archive thumbnail">
        <div class="p-0 pt-2 pb-2">
          <h5 class="mb-0 text-center"><strong>{{ archive.name }}</strong></h5>
        </div>
        </a>
      </div>
    {% endif %}
  {% empty %}
    <p class="text-center w-100">Ingen arkiv er blitt publisert.</p>
  {% endfor %}
  </div>
  {% if is_paginated %}
    <nav>
      <ul class="pagination mb-0">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{% url 'archive:list' %}?side={{ page_obj.previous_page_number }}">Forrige</a>
          </li>
        {% endif %}
          <li class="page-item disabled">
            <a class="page-link" href="#">{{ page_obj.number }} av {{ page_obj.paginator.num_pages }}</a>
          </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{% url 'archive:list' %}?side={{ page_obj.next_page_number }}">Neste</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</div>
<div class="container mt-2 mb-2 p-3 bg-white border">
  <nav aria-label="breadcrumb mb-0">
    <ol class="breadcrumb mb-0">
      <li class="breadcrumb-item"><a href="{% url 'frontpage:index' %}">Forsiden</a></li>
      <li class="breadcrumb-item active" aria-current="page">Arkiv</li>
    </ol>
  </nav>
</div>
{% endblock %}